version: '3.8'

services:
  db:
    image: postgres:13
    container_name: shoe_store_db
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - .docker/data:/var/lib/postgresql/data
    restart: unless-stopped
