"""Update product and size tables and create productsise table

Revision ID: 4b49d786c035
Revises: 7dc2d90c73a9
Create Date: 2025-05-06 10:14:14.559667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b49d786c035'
down_revision: Union[str, None] = '7dc2d90c73a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sizes',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('sizes_product_id_fkey', 'sizes', type_='foreignkey')
    op.drop_column('sizes', 'quantity')
    op.drop_column('sizes', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizes', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sizes', sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('sizes_product_id_fkey', 'sizes', 'products', ['product_id'], ['id'])
    op.drop_table('product_sizes')
    # ### end Alembic commands ###
