"""Update product and size models

Revision ID: 7dc2d90c73a9
Revises: 23db2139f864
Create Date: 2025-05-06 09:18:38.636572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc2d90c73a9'
down_revision: Union[str, None] = '23db2139f864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_size_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'size_id')
    op.drop_column('products', 'quantity')
    op.add_column('sizes', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('sizes', sa.Column('quantity', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(None, 'sizes', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sizes', type_='foreignkey')
    op.drop_column('sizes', 'quantity')
    op.drop_column('sizes', 'product_id')
    op.add_column('products', sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_size_id_fkey', 'products', 'sizes', ['size_id'], ['id'])
    # ### end Alembic commands ###
