"""add nullable=True to patronymic in admin

Revision ID: 82e6ab6343ed
Revises: 801d06cfe701
Create Date: 2025-04-29 12:57:44.606158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e6ab6343ed'
down_revision: Union[str, None] = '801d06cfe701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
