"""Done with nullable

Revision ID: a1ba5d048a2b
Revises: 9db5b2bd38ee
Create Date: 2025-04-29 13:53:36.600177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ba5d048a2b'
down_revision: Union[str, None] = '9db5b2bd38ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('colors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('colors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('admins', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
